In [16]:
import xarray as xr
import numpy as np
import pandas as pd

In [17]:
data = xr.DataArray(np.random.randn(2, 3), dims=("x", "y"), coords={"x": [10, 20]})

data

<xarray.DataArray (x: 2, y: 3)>
array([[ 1.50278272, -0.3297203 ,  0.68902124],
       [-0.78946772,  1.37292636, -0.11262147]])
Coordinates:
  * x        (x) int64 10 20
Dimensions without coordinates: y

In [18]:
xr.DataArray(pd.Series(range(3), index=list("abc"), name="foo"))

<xarray.DataArray 'foo' (dim_0: 3)>
array([0, 1, 2])
Coordinates:
  * dim_0    (dim_0) object 'a' 'b' 'c'

In [21]:
# data.values

# data.dims

data.coords

# data.attrs

Coordinates:
  * x        (x) int64 10 20

In [47]:
data = xr.DataArray( [[1,2],[3,4],[5,6]], dims=("x", "y"), coords={"x": [0,1,2]})
data2 = xr.DataArray( [[1,2],[3,4],[5,6]], dims=("x", "y"))

In [48]:
data.attrs["koniec"] = "tak"

In [49]:
data -  data2

<xarray.DataArray (x: 3, y: 2)>
array([[0, 0],
       [0, 0],
       [0, 0]])
Coordinates:
  * x        (x) int64 0 1 2
Dimensions without coordinates: y

In [59]:
data.name = "Hello"

In [60]:
data

<xarray.DataArray 'Hello' (x: 3, y: 2)>
array([[1, 2],
       [3, 4],
       [5, 6]])
Coordinates:
  * x        (x) int64 0 1 2
Dimensions without coordinates: y
Attributes:
    koniec:   tak

In [66]:
df= pd.DataFrame({"one": [1,2,3,4], "two": [5,6,7,8]})

In [67]:
df

one  two
0    1    5
1    2    6
2    3    7
3    4    8

In [68]:
data = xr.DataArray(df)

In [69]:
data

<xarray.DataArray (dim_0: 4, dim_1: 2)>
array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])
Coordinates:
  * dim_0    (dim_0) int64 0 1 2 3
  * dim_1    (dim_1) object 'one' 'two'

In [76]:
data.sel(dim_1="one")

<xarray.DataArray (dim_0: 4)>
array([1, 2, 3, 4])
Coordinates:
  * dim_0    (dim_0) int64 0 1 2 3
    dim_1    <U3 'one'

In [81]:
data[:,0]

<xarray.DataArray (dim_0: 4)>
array([1, 2, 3, 4])
Coordinates:
  * dim_0    (dim_0) int64 0 1 2 3
    dim_1    <U3 'one'

In [85]:
data.sum(dim="dim_0")

<xarray.DataArray (dim_1: 2)>
array([10, 26])
Coordinates:
  * dim_1    (dim_1) object 'one' 'two'

In [87]:
data.coords = (["idx"])

AttributeError: can't set attribute