# simplex tableau

is structured

```
+---------------+-------------------+
| -c'_bB^(-1)b  |   c'-c'_b B^(-1)A |
+---------------+-------------------+
| B^(-1)b       |  B^(-1)A          |
+---------------+-------------------+
```
meaning:

```

+---------------------------------+-----------------------------+
|    current optim func cost      |  relative cost for each var |
+---------------------------------+-----------------------------+
| values of vars in current base  |  current const coeficients  |
+---------------------------------+-----------------------------+
```

We are minimaizing `-10x1 - 12x2-12x3`

with following constraints
```
1*x1 + 2*x2 + 2*x3 + x4 = 20
2*x1 + x2  + 2*x3 + x5 = 20
2*x1 + 2*x2  + x3 + x6 = 20
x1, ..., x6 >= 0
```

In [30]:
%load_ext autoreload
%autoreload 2
import numpy as np
import simplex as my
import time

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
A = np.array([[1, 1], 
              [0, 1], 
              [1, 2]])
b = np.array([0, 6, 3, 9])
c = np.array([2, 5])


In [18]:
A = np.array([[1, 2, 2], 
              [2, 1, 2], 
              [2, 2, 1]])
b = np.array([0,20, 20, 20])
c = np.array([-10, -12, -12])
A = A.reshape((3,3))
c = c.reshape((1,3))

In [19]:
 s = my.Simplex(A,b,c)
print("A",s.A)
print("b",s.b)
print("c",s.c)

A [[1. 2. 2. 1. 0. 0.]
 [2. 1. 2. 0. 1. 0.]
 [2. 2. 1. 0. 0. 1.]]
b [ 0. 20. 20. 20.]
c [[-10. -12. -12.   0.   0.   0.]]


In [5]:
pass1 = s.optimize()

i 0 col 1 b[i] 20.0 a_val 2.0 row 0 ratio 10.0
i 1 col 1 b[i] 20.0 a_val 1.0 row 1 ratio 20.0
i 2 col 1 b[i] 20.0 a_val 2.0 row 2 ratio 10.0
[[  0. -10. -12. -12.   0.   0.   0.]
 [ 20.   1.   2.   2.   1.   0.   0.]
 [ 20.   2.   1.   2.   0.   1.   0.]
 [ 20.   2.   2.   1.   0.   0.   1.]]

[[120.   -4.    0.    0.    6.    0.    0. ]
 [ 10.    0.5   1.    1.    0.5   0.    0. ]
 [ 10.    1.5   0.    1.   -0.5   1.    0. ]
 [  0.    1.    0.   -1.   -1.    0.    1. ]]
Pivot col:  2
pivot row:  1
2.0


In [6]:
pass2 = s.optimize()

i 0 col 0 b[i] 10.0 a_val 0.5 row 0 ratio 20.0
i 1 col 0 b[i] 10.0 a_val 1.5 row 1 ratio 6.666666666666667
i 2 col 0 b[i] 0.0 a_val 1.0 row 2 ratio 0.0
[[120.   -4.    0.    0.    6.    0.    0. ]
 [ 10.    0.5   1.    1.    0.5   0.    0. ]
 [ 10.    1.5   0.    1.   -0.5   1.    0. ]
 [  0.    1.    0.   -1.   -1.    0.    1. ]]

[[120.    0.    0.   -4.    2.    0.    4. ]
 [ 10.    0.    1.    1.5   1.    0.   -0.5]
 [ 10.    0.    0.    2.5   1.    1.   -1.5]
 [  0.    1.    0.   -1.   -1.    0.    1. ]]
Pivot col:  1
pivot row:  3
1.0


In [13]:
s.optimize()

helllo
helllo
i 2 col 0 b[i] 4.0 a_val 1.0 row 2 ratio 4.0
[[136.    0.    0.    0.    3.6   1.6   1.6]
 [  4.    0.    1.    0.    0.4  -0.6   0.4]
 [  4.    0.    0.    1.    0.4   0.4  -0.6]
 [  4.    1.    0.    0.   -0.6   0.4   0.4]]

[[136.    0.    0.    0.    3.6   1.6   1.6]
 [  4.    0.    1.    0.    0.4  -0.6   0.4]
 [  4.    0.    0.    1.    0.4   0.4  -0.6]
 [  4.    1.    0.    0.   -0.6   0.4   0.4]]
Pivot col:  1
pivot row:  3
1.0


array([[136. ,   0. ,   0. ,   0. ,   3.6,   1.6,   1.6],
       [  4. ,   0. ,   1. ,   0. ,   0.4,  -0.6,   0.4],
       [  4. ,   0. ,   0. ,   1. ,   0.4,   0.4,  -0.6],
       [  4. ,   1. ,   0. ,   0. ,  -0.6,   0.4,   0.4]])

In [15]:
test_itr_1 = np.array([
[120.0,	-4.0,	0.0,	0.0,	6.0,	0.0,	0.0	],
[10.0,	0.5,	1.0,	1.0,	0.5,	0.0,	0.0	],
[10.0,	1.5,	0.0,	1.0,	-0.5,	1.0,	0.0	],
[0.0,	1.0,	0.0,	-1.0,	-1.0,	0.0,	1.0	]
])
assert(np.array_equiv(pass1, test_itr_1))

In [17]:
test_itr_2 = np.array([
[120.0, 0.0, 0.0, -4.0, 2.0, 0.0, 4.0],
[10.0,0.0,1.0,1.5,1.0,0.0,-0.5],
[10.0,0.0,0.0,2.5,1.0,	1.0,	-1.5],
[0.0,1.0,	0.0,	-1.0,	-1.0,	0.0,	1.0],
])
assert(np.array_equiv(pass2, test_itr_2))

In [33]:
s = my.Simplex(A,b,c)
start = time.perf_counter()
s.simplex(4)
stop = time.perf_counter()
print("This all took: ",stop-start)

i 0 col 1 b[i] 20.0 a_val 2.0 row 0 ratio 10.0
i 1 col 1 b[i] 20.0 a_val 1.0 row 1 ratio 20.0
i 2 col 1 b[i] 20.0 a_val 2.0 row 2 ratio 10.0
[[  0. -10. -12. -12.   0.   0.   0.]
 [ 20.   1.   2.   2.   1.   0.   0.]
 [ 20.   2.   1.   2.   0.   1.   0.]
 [ 20.   2.   2.   1.   0.   0.   1.]]

[[120.   -4.    0.    0.    6.    0.    0. ]
 [ 10.    0.5   1.    1.    0.5   0.    0. ]
 [ 10.    1.5   0.    1.   -0.5   1.    0. ]
 [  0.    1.    0.   -1.   -1.    0.    1. ]]
Pivot col:  2
pivot row:  1
2.0
i 0 col 0 b[i] 10.0 a_val 0.5 row 0 ratio 20.0
i 1 col 0 b[i] 10.0 a_val 1.5 row 1 ratio 6.666666666666667
i 2 col 0 b[i] 0.0 a_val 1.0 row 2 ratio 0.0
[[120.   -4.    0.    0.    6.    0.    0. ]
 [ 10.    0.5   1.    1.    0.5   0.    0. ]
 [ 10.    1.5   0.    1.   -0.5   1.    0. ]
 [  0.    1.    0.   -1.   -1.    0.    1. ]]

[[120.    0.    0.   -4.    2.    0.    4. ]
 [ 10.    0.    1.    1.5   1.    0.   -0.5]
 [ 10.    0.    0.    2.5   1.    1.   -1.5]
 [  0.    1.    0.   -1