# simplex tableau

is structured

```
+---------------+-------------------+
| -c'_bB^(-1)b  |   c'-c'_b B^(-1)A |
+---------------+-------------------+
| B^(-1)b       |  B^(-1)A          |
+---------------+-------------------+
```
meaning:

```

+---------------------------------+-----------------------------+
|    current optim func cost      |  relative cost for each var |
+---------------------------------+-----------------------------+
| values of vars in current base  |  current const coeficients  |
+---------------------------------+-----------------------------+
```

We are minimaizing `-10x1 - 12x2-12x3`

with following constraints
```
1*x1 + 2*x2 + 2*x3 + x4 = 20
2*x1 + x2  + 2*x3 + x5 = 20
2*x1 + 2*x2  + x3 + x6 = 20
x1, ..., x6 >= 0
```

In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
import simplex as my

In [2]:
A = np.array([[1, 1], 
              [0, 1], 
              [1, 2]])
b = np.array([0, 6, 3, 9])
c = np.array([2, 5])


In [3]:
A = np.array([[1, 2, 2], 
              [2, 1, 2], 
              [2, 2, 1]])
b = np.array([0,20, 20, 20])
c = np.array([-10, -12, -12])
A = A.reshape((3,3))
c = c.reshape((1,3))

In [4]:
 s = my.Simplex(A,b,c)

In [5]:
s.optimize()

[[  0. -10. -12. -12.   0.   0.   0.]
 [ 20.   1.   2.   2.   1.   0.   0.]
 [ 20.   2.   1.   2.   0.   1.   0.]
 [ 20.   2.   2.   1.   0.   0.   1.]]

[[ 0.5  1.   1.   0.5  0.   0. ]
 [ 1.5  0.   1.  -0.5  1.   0. ]
 [ 1.   0.  -1.  -1.   0.   1. ]]
[120.  10.  10.   0.]
[-4.  0.  0.  6.  0.  0.]


array([[120. ,  -4. ,   0. ,   0. ,   6. ,   0. ,   0. ],
       [ 10. ,   0.5,   1. ,   1. ,   0.5,   0. ,   0. ],
       [ 10. ,   1.5,   0. ,   1. ,  -0.5,   1. ,   0. ],
       [  0. ,   1. ,   0. ,  -1. ,  -1. ,   0. ,   1. ]])

In [6]:
test_itr_1 = np.array([
[120.0,	-4.0,	0.0,	0.0,	6.0,	0.0,	0.0	],
[10.0,	0.5,	1.0,	1.0,	0.5,	0.0,	0.0	],
[10.0,	1.5,	0.0,	1.0,	-0.5,	1.0,	0.0	],
[0.0,	1.0,	0.0,	-1.0,	-1.0,	0.0,	1.0	]
])
# assert(np.array_equiv(s.optimize(), test_itr_1))